package br.com.clinicaformare.dao.calendario;

public enum CalendarioDiasUteis {
	SEMSABADO_SEMDOMINGO_SEMFERIADO, SEMSABADO_SEMDOMINGO, SEMDOMINGO_SEMFERIADO, SEMDOMINGO, SEMSABADO_SEMDOMINGO_SEMFERIADO2
}
